CREATE TABLE phrases (
  id     SERIAL       NOT NULL PRIMARY KEY,
  text   VARCHAR(150) NOT NULL UNIQUE,
  image  VARCHAR(100) NOT NULL DEFAULT '',
  notes  VARCHAR(500) NOT NULL DEFAULT '',
  date   DATE         NOT NULL DEFAULT CURRENT_DATE
);
